env: safetyGraphics
label: Tplyr Interactive Demo Table
type: module
package: Tplyr
export: true
order: 1
domain:
  - dm
  - labs
  - aes
workflow:
  ui: mod_tplyr_demo_ui
  server: mod_tplyr_demo_server
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
